### ISSUE TITLE
Ti namespace & no more BCALL

### ISSUE THREAD

**Issue by FatherOfEgg** [jacobly0/fasmg-z80#2]
Would it be of any interest to put ti83plusg.inc under a namespace?

```
namespace ti
...
?PutS		equ 450Ah
...
end namespace
```

Then change the bcall/bjump macro to be something like:
```
iterate <name,instruction>, call,rst 28h, jump,call 50h
	macro name address*
		rawmatch ti_namespace.addr, address
			instruction
			dw address
		else rawmatch =jump?, name
			instruction
			dw address
		else
			call address
		end rawmatch
	end macro
end iterate
```

So instead of `bcall _PutS` it would be `call ti.PutS`. Now there won't be two different call instructions, it would just be `call <something>`.

**Comment by jacobly0** [comment]
That would match any namespace which is something I do [all the time](https://github.com/CE-Programming/toolchain/blob/usbdrvce/src/usbdrvce/usbdrvce.asm#L767).  The proper way would be to base all of the bcalls on an element and then check if the address is relative to that in `call`/`jp` wrappers.  Also, the sed script already adds a namespace.

**Comment by FatherOfEgg** [comment]
Sorry for bothering you again, hope you don't mind me asking you two questions.

1) I totally forgot that the sed script was there. Anyway, it gives me an error due to the fact that there are two `cxMain`. One of them originally had an "_" before it, so I was wondering if I should put back the underscore, or do something else. Any suggestions?

2) For the `hello.asm` in the tests, is there a reason why the `call` isn't a `bcall`?
