### ISSUE TITLE
Points from DeZog debugging thread

### ISSUE THREAD

**Issue by stevexyz** [jacobly0/fasmg-z80#3]
Dear @jacobly0, since these are more fasmg-ez80 specific, if good for you I would continue here the discussion of the listing for DeZog. 

I report here the points:

1. I din't know that you created also a "Z80" version, and I always used the EZ80 one with the `assume adl = 0` (as you suggested [here](https://board.flatassembler.net/topic.php?t=19201)): which are the differences?

2. if you implement a new listing to be directly compatible with DeZog even better, but in the meantime can I ask if you are able to add the variable value (in the "equ" or "=" instruction) in the current listing [here](https://github.com/stevexyz/DeZog/blob/fasmg-ez80/examples/zx80zx81-1k-kit%20v2/includes/fasmgutils.inc)? Currently I'm able to convert when is a direct value, but when is an expression I'm not able to extract the value (e.g. line 251 [here](https://github.com/stevexyz/DeZog/blob/fasmg-ez80/examples/zx80zx81-1k-kit%20v2/simpleexamplezx81.lst))

Thank you

**Comment by stevexyz** [comment]
1. I'm developing for Z80 based Sinclair ZX80 and ZX81, then I'll try to use then the new Z80.inc (anyway the old ez80 maybe not so quick, as fasmg in general, but was very good! :))
2. For this I leave it in your hands: as said I like fasmg but I'm more like an "end user" in this respect! For now anyway if the old listing will work the same I have completed [the listing "translator" for DeZog](https://github.com/stevexyz/DeZog/blob/fasmg-ez80/examples/zx80zx81-1k-kit%20v2/makesld.py), and if it will not work I''ll continue to use the old ez80, in the meantime
Thank you!

**Comment by jacobly0** [comment]
Closing with https://github.com/stevexyz/DeZog/pull/1.
