### ISSUE TITLE
Possible error on xor parsing

### ISSUE THREAD

**Issue by stevexyz** [jacobly0/fasmg-z80#4]
I'm trying to switch from the "old" ez80.inc to z80.inc but I got a strange error parsing the xor instruction ("simple-zx81-example.asm [25]: xor a  ? [42] (CALM) Error: the value of symbol 'xor?' is not valid for this use.").
I'm not sure if I'm doing something wrong, in the ez80 I was using "xor a,a" syntax, but I tried also the "xor a" syntax (and "xor b") without success.
I've created a branch here https://github.com/stevexyz/DeZog/tree/z80inc-xoraerror/examples/fasmg-dezog-zx81kit with the asm file modified to reproduce the error.

**Comment by stevexyz** [comment]
I verified and seems that the probrem is generated by the makesld.alm include file; in fact removing it the file is assembled

**Comment by jacobly0** [comment]
Closing with stevexyz/DeZog#2.
