### ISSUE TITLE
Another issue found in makesld

### ISSUE THREAD

**Issue by stevexyz** [jacobly0/fasmg-z80#5]
Seems that the "makesld" create problems when something as the following code is added in the source file:
```
somebytes equ 0,1,2,3 ; first part defined
db somebytes,4,5,6,7 ; instanciated and second part added
```
(I've used this structure quite a lot, and with more than 4 values as in the example)

I've made a little branch on the kit repository to reproduce the behaviour:
https://github.com/stevexyz/fasmg-dezog-zx81kit/tree/error2

**Comment by jacobly0** [comment]
If you require me to support using `equ` for constants (which is not what it is meant for) then I can't also support it being used for non-constants.

I would suggest either using the more correct `:=` for constants, which means I can just ignore `equ`, or specifically use `define` for non-constants.

**Comment by stevexyz** [comment]
I've tryed with define and it is working (the := was not working with list of numbers):
```
define somebytes 0,1,2,3 ; first part defined
db somebytes,4,5,6,7 ; instanciated and second part added
```
Fine for me: I'll easily convert my 100+ lines of equs to this format.
Thank you!

**Comment by stevexyz** [comment]
PS: just willing to mention that is incredible the speed of the new "calm" version!!
(my 200kb source file is compiled in 0.1 seconds, while before would require some seconds, and additional tools to create symbolic informations!)
Great Jacob!
